
package com.etc.bca_moto.ui;

import java.util.Random;

import com.etc.bca_moto.business.MyAuthenticationProvider;
import com.etc.bca_moto.business.MyAuthorizationConfigurationProvider;
import com.vaadin.event.ShortcutAction;
import com.vaadin.server.FontAwesome;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.xdev.res.ApplicationResource;
import com.xdev.security.authentication.CredentialsUsernamePassword;
import com.xdev.security.authentication.ui.Authentication;
import com.xdev.ui.XdevAbsoluteLayout;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPasswordField;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;

public class LoginView extends XdevView implements com.xdev.security.authentication.ui.LoginView {

	/**
	 * 
	 */
	private final Random rdm = new Random();

	public LoginView() {
		super();
		this.initUI();
		setMaBaoMat();
	}

	@Override
	public String getPassword() {
		return this.txtPassword.getValue();
	}

	@Override
	public String getUsername() {
		return this.txtUsername.getValue();
	}

	public void setMaBaoMat() {
		String rd = String.valueOf(this.rdm.nextInt(9999));
		while (rd.length() < 4) {
			rd = "0" + rd;
		}
		this.txtRandom.setValue(rd);
	}
	// e19d5cd5af0378da05f63f891c7467af - abcd1234
	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdLogin}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdLogin_buttonClick(final Button.ClickEvent event) {
		final CredentialsUsernamePassword credentials = CredentialsUsernamePassword.New(getUsername(), getPassword());
		final MyAuthenticationProvider authenticatorProvider = MyAuthenticationProvider.getInstance();
		final MyAuthorizationConfigurationProvider authorizationConfigurationProvider = null;
				//MyAuthorizationConfigurationProvider.getInstance();
		if (this.txtMaBaoVe.getValue().equals(this.txtRandom.getValue())) {
			if (!Authentication.tryLogin(credentials, authenticatorProvider,authorizationConfigurationProvider)) {
				Notification.show("Tài khoản hoặc mật khẩu không chính xác!", Type.ERROR_MESSAGE);
				setMaBaoMat();
			}
		} else {
			Notification.show("Mã bảo mật không chính xác!", Type.WARNING_MESSAGE);
			setMaBaoMat();
		}
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #btnRandom}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnRandom_buttonClick(final Button.ClickEvent event) {
		setMaBaoMat();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.absoluteLayoutBanner = new XdevAbsoluteLayout();
		this.lblBCA = new XdevLabel();
		this.image = new Image();
		this.absoluteLayout = new XdevAbsoluteLayout();
		this.label = new XdevLabel();
		this.txtUsername = new XdevTextField();
		this.txtPassword = new XdevPasswordField();
		this.txtMaBaoVe = new XdevTextField();
		this.cmdLogin = new XdevButton();
		this.txtRandom = new XdevTextField();
		this.btnRandom = new XdevButton();
		this.absoluteLayoutFooter = new XdevAbsoluteLayout();
		this.lblFooter = new XdevLabel();
	
		this.setPrimaryStyleName("auth_view_background");
		this.gridLayout.setMargin(new MarginInfo(false));
		this.lblBCA.setStyleName("large");
		this.lblBCA.setValue(
				"<b style=\"color:#FBC50A;\">BỘ CÔNG AN<br>CỤC CẢNH SÁT GIAO THÔNG</b><br><b style=\"color:#FFF;\"> HỆ THỐNG CƠ SỞ DỮ LIỆU XỬ PHẠT VI PHẠM HÀNH CHÍNH TRONG LĨNH VỰC GIAO THÔNG</b>");
		this.lblBCA.setContentMode(ContentMode.HTML);
		this.image.setSource(
				new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/image_2019removebg.png"));
		this.label.setStyleName("h3");
		this.label.setValue("<div style=\"text-align: center;width:100%;color:#085B97\"><b >ĐĂNG NHẬP TÀI KHOẢN</b></div>");
		this.label.setContentMode(ContentMode.HTML);
		this.txtUsername.setCaption("Tài khoản");
		this.txtUsername.setInputPrompt("Nhập tài khoản");
		this.txtPassword.setCaption("Mật khẩu");
		this.txtPassword.setInputPrompt("..............");
		this.txtMaBaoVe.setInputPrompt("Nhập mã bảo vệ");
		this.cmdLogin.setCaption("ĐĂNG NHẬP");
		this.cmdLogin.setPrimaryStyleName("v-btnLuu");
		this.cmdLogin.setClickShortcut(ShortcutAction.KeyCode.ENTER);
		this.txtRandom.setEnabled(false);
		this.txtRandom.setPrimaryStyleName("captcha_background");
		this.btnRandom.setIcon(FontAwesome.REPEAT);
		this.btnRandom.setCaption("");
		this.btnRandom.setPrimaryStyleName("v-btnLuu");
		this.lblFooter.setValue(
				"<div style=\"font-size: 12px;color:#FFF;text-align:center\"><b>CỤC CẢNH SÁT GIAO THÔNG</b><br> Địa chỉ: 112 Lê Duẩn, Quận Hoàn Kiếm, Hà Nội<br>Fax:84 24 38220885 * Email:tccs-c67@vnn.vn * Đường dây nóng: 0692342608 * Phiên bản 0.55</div>");
		this.lblFooter.setContentMode(ContentMode.HTML);
	
		this.lblBCA.setWidth(100, Unit.PERCENTAGE);
		this.lblBCA.setHeight(100, Unit.PIXELS);
		this.absoluteLayoutBanner.addComponent(this.lblBCA, "left:140px; top:20px");
		this.image.setWidth(110, Unit.PIXELS);
		this.image.setHeight(120, Unit.PIXELS);
		this.absoluteLayoutBanner.addComponent(this.image, "left:123px; top:0px");
		this.label.setWidth(400, Unit.PIXELS);
		this.absoluteLayout.addComponent(this.label, "left:37px; top:51px");
		this.txtUsername.setWidth(400, Unit.PIXELS);
		this.absoluteLayout.addComponent(this.txtUsername, "left:37px; top:147px");
		this.txtPassword.setWidth(400, Unit.PIXELS);
		this.absoluteLayout.addComponent(this.txtPassword, "left:38px; top:216px");
		this.txtMaBaoVe.setWidth(300, Unit.PIXELS);
		this.txtMaBaoVe.setHeight(37, Unit.PIXELS);
		this.absoluteLayout.addComponent(this.txtMaBaoVe, "left:38px; top:266px");
		this.cmdLogin.setWidth(150, Unit.PIXELS);
		this.cmdLogin.setHeight(40, Unit.PIXELS);
		this.absoluteLayout.addComponent(this.cmdLogin, "left:160px; top:340px");
		this.txtRandom.setWidth(80, Unit.PIXELS);
		this.txtRandom.setHeight(37, Unit.PIXELS);
		this.absoluteLayout.addComponent(this.txtRandom, "left:358px; top:266px");
		this.btnRandom.setWidth(40, Unit.PIXELS);
		this.btnRandom.setHeight(38, Unit.PIXELS);
		this.absoluteLayout.addComponent(this.btnRandom, "left:448px; top:266px");
		this.lblFooter.setWidth(100, Unit.PERCENTAGE);
		this.lblFooter.setHeight(100, Unit.PERCENTAGE);
		this.absoluteLayoutFooter.addComponent(this.lblFooter, "left:1px; top:30px");
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(3);
		this.absoluteLayoutBanner.setWidth(1100, Unit.PIXELS);
		this.absoluteLayoutBanner.setHeight(150, Unit.PIXELS);
		this.gridLayout.addComponent(this.absoluteLayoutBanner, 0, 0);
		this.gridLayout.setComponentAlignment(this.absoluteLayoutBanner, Alignment.TOP_CENTER);
		this.absoluteLayout.setWidth(500, Unit.PIXELS);
		this.absoluteLayout.setHeight(700, Unit.PIXELS);
		this.gridLayout.addComponent(this.absoluteLayout, 0, 1);
		this.gridLayout.setComponentAlignment(this.absoluteLayout, Alignment.MIDDLE_CENTER);
		this.absoluteLayoutFooter.setWidth(600, Unit.PIXELS);
		this.absoluteLayoutFooter.setHeight(100, Unit.PIXELS);
		this.gridLayout.addComponent(this.absoluteLayoutFooter, 0, 2);
		this.gridLayout.setComponentAlignment(this.absoluteLayoutFooter, Alignment.BOTTOM_CENTER);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setWidth(100, Unit.PERCENTAGE);
		this.setHeight(-1, Unit.PIXELS);
	
		this.cmdLogin.addClickListener(event -> this.cmdLogin_buttonClick(event));
		this.btnRandom.addClickListener(event -> this.btnRandom_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel label, lblBCA, lblFooter;
	private XdevButton cmdLogin, btnRandom;
	private XdevAbsoluteLayout absoluteLayout, absoluteLayoutBanner, absoluteLayoutFooter;
	private Image image;
	private XdevPasswordField txtPassword;
	private XdevGridLayout gridLayout;
	private XdevTextField txtUsername, txtMaBaoVe, txtRandom;
	// </generated-code>

}
