
package com.etc.bca_moto.ui;

import com.etc.bca_moto.dal.QdGiamMienTienPhat04DAO;
import com.etc.bca_moto.entities.QdGiamMienTienPhat04;
import com.etc.bca_moto.entities.QdGiamMienTienPhat04_;
import com.vaadin.data.Property;
import com.vaadin.ui.Button;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.xdev.dal.DAOs;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.table.XdevTable;

public class MainView extends XdevView {

	/**
	 * 
	 */
	public MainView() {
		super();
		this.initUI();
	}

	/**
	 * Event handler delegate method for the {@link XdevTable} {@link #table}.
	 *
	 * @see Property.ValueChangeListener#valueChange(Property.ValueChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void table_valueChange(final Property.ValueChangeEvent event) {
		final QdGiamMienTienPhat04 phat04 = this.table.getSelectedItem().getBean();
		final Window w = new Window("QUYẾT ĐỊNH GIẢM MIỄN VI PHẠM HÀNH CHÍNH");
		w.setWidth(1300,Unit.PIXELS);
		w.setHeight(80,Unit.PERCENTAGE);
		w.setResizable(false);
		w.setModal(true);
		UI.getCurrent().getSession().setAttribute("OutPutViewReport04", phat04);
		w.setContent(new BBGiamPhatView());
		UI.getCurrent().addWindow(w);
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #btnBBvphc}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnBBvphc_buttonClick(final Button.ClickEvent event) {
		
		final Window w = new Window("BIÊN BẢN VI PHẠM HÀNH CHÍNH");
		w.setWidth(70,Unit.PERCENTAGE);
		w.setHeight(90,Unit.PERCENTAGE);
		w.setResizable(false);
		w.setModal(true);
		w.setContent(BBVPHCView.getInstance());
		
		UI.getCurrent().addWindow(w);
		
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.btnBBvphc = new XdevButton();
		this.table = new XdevTable<>();
	
		this.btnBBvphc.setCaption("Create Report");
		this.btnBBvphc.setPrimaryStyleName("v-btnLuu");
		this.table.setContainerDataSource(QdGiamMienTienPhat04.class, DAOs.get(QdGiamMienTienPhat04DAO.class).findAll());
		this.table.setVisibleColumns(QdGiamMienTienPhat04_.coQuanChuQuan.getName(), QdGiamMienTienPhat04_.donVi.getName(),
				QdGiamMienTienPhat04_.capBacChucVu.getName(), QdGiamMienTienPhat04_.soQuyetDinh.getName(),
				QdGiamMienTienPhat04_.ngayTaoQuyetDinh.getName(), QdGiamMienTienPhat04_.tenNguoiNvp.getName(),
				QdGiamMienTienPhat04_.lyDoGiam.getName(), QdGiamMienTienPhat04_.tangVatNhanLai.getName(),
				QdGiamMienTienPhat04_.trangThaiQd.getName());
		this.table.setColumnHeader("coQuanChuQuan", "Cơ quan chủ quản");
		this.table.setColumnHeader("donVi", "Đơn vị");
		this.table.setColumnHeader("capBacChucVu", "Cấp bậc");
		this.table.setColumnHeader("soQuyetDinh", "Số QĐ");
		this.table.setColumnHeader("ngayTaoQuyetDinh", "Ngày tạo QĐ");
		this.table.setColumnHeader("tenNguoiNvp", "Người vi phạm");
		this.table.setColumnHeader("lyDoGiam", "Lý do giảm");
		this.table.setColumnHeader("tangVatNhanLai", "Tang vật nhận lại");
		this.table.setColumnHeader("trangThaiQd", "Trạng thái");
	
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(2);
		this.btnBBvphc.setSizeUndefined();
		this.gridLayout.addComponent(this.btnBBvphc, 0, 0);
		this.table.setSizeFull();
		this.gridLayout.addComponent(this.table, 0, 1);
		this.gridLayout.setRowExpandRatio(1, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.btnBBvphc.addClickListener(event -> this.btnBBvphc_buttonClick(event));
		this.table.addValueChangeListener(new Property.ValueChangeListener() {
			@Override
			public void valueChange(final Property.ValueChangeEvent event) {
				MainView.this.table_valueChange(event);
			}
		});
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton btnBBvphc;
	private XdevGridLayout gridLayout;
	private XdevTable<QdGiamMienTienPhat04> table;
	// </generated-code>

}
