
package com.etc.bca_moto.ui;

import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.server.VaadinRequest;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.shared.ui.ui.Transport;
import com.xdev.security.authentication.ui.XdevAuthenticationNavigator;
import com.xdev.ui.XdevUI;

@Push(value = PushMode.MANUAL, transport = Transport.LONG_POLLING)
@Theme("BCA_MOTO")
public class MainUI extends XdevUI {
	public MainUI() {
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void init(final VaadinRequest request) {
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.navigator = new XdevAuthenticationNavigator(this, this);
	
		this.setTabIndex(0);
		this.navigator.setRedirectViewName("home");
		this.navigator.addView("", LoginView.class);
		this.navigator.addView("home", MainView.class);
	
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevAuthenticationNavigator navigator;
	// </generated-code>
}