package com.etc.bca_moto.ui;

import com.vaadin.data.Property;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Window;
import com.xdev.ui.XdevAbsoluteLayout;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;

public class OptionTVPTGTView extends XdevView{

	/**
	 * 
	 */
	private static OptionTVPTGTView instance;
	
	public OptionTVPTGTView() {
		super();
		this.initUI();
		this.absLayoutGPLX.setVisible(false);
		this.absLayoutKiemDinh.setVisible(false);
		this.absLayoutPhuongTien.setVisible(false);
		this.absLayoutDangKy.setVisible(false);
		}
	
	public static OptionTVPTGTView getInstance(){
		if(instance==null){
			instance = new OptionTVPTGTView();
		}
		return instance;
		
	}
	/**
	 * Event handler delegate method for the {@link CheckBox} {@link #cbGPLX}.
	 *
	 * @see Property.ValueChangeListener#valueChange(Property.ValueChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cbGPLX_valueChange(final Property.ValueChangeEvent event) {
		if(this.cbGPLX.getValue()){
			this.absLayoutGPLX.setVisible(true);
		} else {
			this.absLayoutGPLX.setVisible(false);
		}
	}

	/**
	 * Event handler delegate method for the {@link CheckBox} {@link #cbKiemDinh}.
	 *
	 * @see Property.ValueChangeListener#valueChange(Property.ValueChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cbKiemDinh_valueChange(final Property.ValueChangeEvent event) {
		if(this.cbKiemDinh.getValue()){
			this.absLayoutKiemDinh.setVisible(true);
		} else {
			this.absLayoutKiemDinh.setVisible(false);
		}
	}

	/**
	 * Event handler delegate method for the {@link CheckBox} {@link #cbDangKy}.
	 *
	 * @see Property.ValueChangeListener#valueChange(Property.ValueChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cbDangKy_valueChange(final Property.ValueChangeEvent event) {
		if(this.cbDangKy.getValue()){
			this.absLayoutDangKy.setVisible(true);
		} else {
			this.absLayoutDangKy.setVisible(false);
		}
	}

	/**
	 * Event handler delegate method for the {@link CheckBox} {@link #cbPhuongTien}.
	 *
	 * @see Property.ValueChangeListener#valueChange(Property.ValueChangeEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cbPhuongTien_valueChange(final Property.ValueChangeEvent event) {
		if(this.cbPhuongTien.getValue()){
			this.absLayoutPhuongTien.setVisible(true);
		} else {
			this.absLayoutPhuongTien.setVisible(false);
		}
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #btnClose}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnClose_buttonClick(final Button.ClickEvent event) {
		BBVPHCView.getInstance().setEnabled(true);
		((Window)this.getParent()).close();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.absoluteLayout = new XdevAbsoluteLayout();
		this.label = new Label();
		this.cbPhuongTien = new CheckBox();
		this.cbDangKy = new CheckBox();
		this.cbGPLX = new CheckBox();
		this.cbKiemDinh = new CheckBox();
		this.absLayoutGPLX = new AbsoluteLayout();
		this.label3 = new Label();
		this.label5 = new Label();
		this.popupDateField = new PopupDateField();
		this.label4 = new Label();
		this.comboBox = new XdevComboBox<>();
		this.label2 = new Label();
		this.textField4 = new TextField();
		this.label12 = new Label();
		this.textField5 = new TextField();
		this.comboBox2 = new XdevComboBox<>();
		this.absLayoutKiemDinh = new AbsoluteLayout();
		this.label6 = new Label();
		this.label7 = new Label();
		this.textField = new TextField();
		this.label8 = new Label();
		this.popupDateField2 = new PopupDateField();
		this.absLayoutDangKy = new AbsoluteLayout();
		this.label9 = new Label();
		this.textField2 = new TextField();
		this.label10 = new Label();
		this.comboBox4 = new XdevComboBox<>();
		this.textField6 = new TextField();
		this.absLayoutPhuongTien = new AbsoluteLayout();
		this.label11 = new Label();
		this.textField3 = new TextField();
		this.absoluteLayout3 = new AbsoluteLayout();
		this.btnSave = new Button();
		this.btnClose = new Button();
	
		this.setPrimaryStyleName("v-font-ct");
		this.gridLayout.setPrimaryStyleName("v-gridlayout-scroll");
		this.gridLayout.setAutoFill(XdevGridLayout.AutoFill.VERTICAL);
		this.label.setCaption("");
		this.label.setCaptionAsHtml(true);
		this.label.setValue("Chọn loại:");
		this.cbPhuongTien.setCaption("Phương Tiện");
		this.cbDangKy.setCaption("Đăng ký");
		this.cbGPLX.setCaption("GPLX");
		this.cbKiemDinh.setCaption("Kiểm định");
		this.absLayoutGPLX.setStyleName("outside-range");
		this.label3.setValue("Hạng");
		this.label5.setValue("có giá trị đến:");
		this.label4.setValue("nơi cấp:");
		this.comboBox.setItemCaptionFromAnnotation(false);
		this.comboBox.setStyleName("borderless");
		this.label2.setCaption("");
		this.label2.setValue("Tạm giữ 01 giáy phép lái xe:");
		this.textField4.setInputPrompt("...................................");
		this.textField4.setStyleName("borderless");
		this.label12.setValue("số:<b style=\"color:red;\">*</b>");
		this.label12.setContentMode(ContentMode.HTML);
		this.textField5.setColumns(5);
		this.textField5.setInputPrompt("...................................");
		this.textField5.setStyleName("borderless");
		this.comboBox2.setItemCaptionFromAnnotation(false);
		this.comboBox2.setStyleName("borderless");
		this.label6.setValue("Tạm giữ 01 giấy chứng nhận kiểm định an toàn kỹ thuật bảo vệ môi trường");
		this.label7.setValue("Số:<b style=\"color:red;\">*</b>");
		this.label7.setContentMode(ContentMode.HTML);
		this.textField.setColumns(5);
		this.textField.setInputPrompt("...................................");
		this.textField.setStyleName("borderless");
		this.label8.setValue("có giá trị đến:");
		this.label9.setValue("Tạm giữ 01 giấy đăng ký xe số:<b style=\"color:red;\">*</b>");
		this.label9.setContentMode(ContentMode.HTML);
		this.textField2.setInputPrompt("...............................................................");
		this.textField2.setStyleName("borderless");
		this.textField2.setRequired(true);
		this.label10.setValue("nơi cấp:&emsp;");
		this.label10.setContentMode(ContentMode.HTML);
		this.comboBox4.setItemCaptionFromAnnotation(false);
		this.comboBox4.setStyleName("borderless");
		this.textField6.setInputPrompt("..............................................................");
		this.textField6.setStyleName("borderless");
		this.textField6.setRequired(true);
		this.label11.setValue("Tạm giữ phương tiện BKS <b style=\"color:red;\">*</b>");
		this.label11.setContentMode(ContentMode.HTML);
		this.textField3.setInputPrompt(".....................................");
		this.textField3.setStyleName("borderless");
		this.textField3.setRequired(true);
		this.btnSave.setCaption("Lưu");
		this.btnSave.setStyleName("outside-range");
		this.btnClose.setCaption("Đóng");
		this.btnClose.setStyleName("outside-range");
	
		this.absoluteLayout.addComponent(this.label, "left:100px; top:10px");
		this.absoluteLayout.addComponent(this.cbPhuongTien, "left:300px; top:100px");
		this.absoluteLayout.addComponent(this.cbDangKy, "left:300px; top:70px");
		this.absoluteLayout.addComponent(this.cbGPLX, "left:300px; top:10px");
		this.absoluteLayout.addComponent(this.cbKiemDinh, "left:300px; top:40px");
		this.label3.setWidth(50, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.label3, "left:50px; top:25px");
		this.label5.setWidth(100, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.label5, "left:353px; top:25px");
		this.popupDateField.setHeight(30, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.popupDateField, "left:452px; top:23px");
		this.label4.setWidth(80, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.label4, "left:700px; top:25px");
		this.comboBox.setWidth(40, Unit.PIXELS);
		this.comboBox.setHeight(30, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.comboBox, "left:100px; top:25px");
		this.absLayoutGPLX.addComponent(this.label2, "left:50px; top:0px");
		this.textField4.setWidth(10, Unit.PERCENTAGE);
		this.textField4.setHeight(25, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.textField4, "left:212px; top:25px");
		this.label12.setWidth(50, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.label12, "left:163px; top:25px");
		this.textField5.setHeight(25, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.textField5, "left:820px; top:25px");
		this.comboBox2.setWidth(40, Unit.PIXELS);
		this.comboBox2.setHeight(30, Unit.PIXELS);
		this.absLayoutGPLX.addComponent(this.comboBox2, "left:781px; top:25px");
		this.label6.setWidth(100, Unit.PERCENTAGE);
		this.absLayoutKiemDinh.addComponent(this.label6, "left:50px; top:1px");
		this.label7.setHeight(25, Unit.PIXELS);
		this.absLayoutKiemDinh.addComponent(this.label7, "left:50px; top:25px");
		this.textField.setHeight(25, Unit.PIXELS);
		this.absLayoutKiemDinh.addComponent(this.textField, "left:50px; top:25px");
		this.absLayoutKiemDinh.addComponent(this.label8, "left:260px; top:25px");
		this.popupDateField2.setHeight(30, Unit.PIXELS);
		this.absLayoutKiemDinh.addComponent(this.popupDateField2, "left:360px; top:25px");
		this.label9.setWidth(220, Unit.PIXELS);
		this.absLayoutDangKy.addComponent(this.label9, "left:50px; top:0px");
		this.textField2.setWidth(30, Unit.PERCENTAGE);
		this.textField2.setHeight(25, Unit.PIXELS);
		this.absLayoutDangKy.addComponent(this.textField2, "left:269px; top:0px");
		this.label10.setWidth(90, Unit.PIXELS);
		this.absLayoutDangKy.addComponent(this.label10, "left:520px; top:0px");
		this.comboBox4.setWidth(40, Unit.PIXELS);
		this.comboBox4.setHeight(30, Unit.PIXELS);
		this.absLayoutDangKy.addComponent(this.comboBox4, "left:620px; top:0px");
		this.textField6.setWidth(80, Unit.PERCENTAGE);
		this.textField6.setHeight(25, Unit.PIXELS);
		this.absLayoutDangKy.addComponent(this.textField6, "left:669px; top:0px");
		this.label11.setWidth(100, Unit.PERCENTAGE);
		this.absLayoutPhuongTien.addComponent(this.label11, "left:50px; top:0px");
		this.textField3.setWidth(60, Unit.PERCENTAGE);
		this.textField3.setHeight(25, Unit.PIXELS);
		this.absLayoutPhuongTien.addComponent(this.textField3, "left:250px; top:0px");
		this.absoluteLayout3.addComponent(this.btnSave, "left:256px; top:10px");
		this.absoluteLayout3.addComponent(this.btnClose, "left:362px; top:10px");
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(6);
		this.absoluteLayout.setWidth(100, Unit.PERCENTAGE);
		this.absoluteLayout.setHeight(124, Unit.PIXELS);
		this.gridLayout.addComponent(this.absoluteLayout, 0, 0);
		this.absLayoutGPLX.setWidth(100, Unit.PERCENTAGE);
		this.absLayoutGPLX.setHeight(70, Unit.PIXELS);
		this.gridLayout.addComponent(this.absLayoutGPLX, 0, 1);
		this.absLayoutKiemDinh.setWidth(100, Unit.PERCENTAGE);
		this.absLayoutKiemDinh.setHeight(70, Unit.PIXELS);
		this.gridLayout.addComponent(this.absLayoutKiemDinh, 0, 2);
		this.absLayoutDangKy.setWidth(100, Unit.PERCENTAGE);
		this.absLayoutDangKy.setHeight(50, Unit.PIXELS);
		this.gridLayout.addComponent(this.absLayoutDangKy, 0, 3);
		this.absLayoutPhuongTien.setWidth(100, Unit.PERCENTAGE);
		this.absLayoutPhuongTien.setHeight(50, Unit.PIXELS);
		this.gridLayout.addComponent(this.absLayoutPhuongTien, 0, 4);
		this.absoluteLayout3.setWidth(100, Unit.PERCENTAGE);
		this.absoluteLayout3.setHeight(70, Unit.PIXELS);
		this.gridLayout.addComponent(this.absoluteLayout3, 0, 5);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(1, 10.0F);
		this.gridLayout.setRowExpandRatio(2, 10.0F);
		this.gridLayout.setRowExpandRatio(5, 10.0F);
		this.gridLayout.setWidth(100, Unit.PERCENTAGE);
		this.gridLayout.setHeight(-1, Unit.PIXELS);
		this.setContent(this.gridLayout);
		this.setWidth(100, Unit.PERCENTAGE);
		this.setHeight(-1, Unit.PIXELS);
	
		this.cbPhuongTien.addValueChangeListener(new Property.ValueChangeListener() {
			@Override
			public void valueChange(final Property.ValueChangeEvent event) {
				OptionTVPTGTView.this.cbPhuongTien_valueChange(event);
			}
		});
		this.cbDangKy.addValueChangeListener(new Property.ValueChangeListener() {
			@Override
			public void valueChange(final Property.ValueChangeEvent event) {
				OptionTVPTGTView.this.cbDangKy_valueChange(event);
			}
		});
		this.cbGPLX.addValueChangeListener(new Property.ValueChangeListener() {
			@Override
			public void valueChange(final Property.ValueChangeEvent event) {
				OptionTVPTGTView.this.cbGPLX_valueChange(event);
			}
		});
		this.cbKiemDinh.addValueChangeListener(new Property.ValueChangeListener() {
			@Override
			public void valueChange(final Property.ValueChangeEvent event) {
				OptionTVPTGTView.this.cbKiemDinh_valueChange(event);
			}
		});
		this.btnClose.addClickListener(event -> this.btnClose_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private Button btnSave, btnClose;
	private TextField textField4, textField5, textField, textField2, textField6, textField3;
	private XdevAbsoluteLayout absoluteLayout;
	private CheckBox cbPhuongTien, cbDangKy, cbGPLX, cbKiemDinh;
	private Label label, label3, label5, label4, label2, label12, label6, label7, label8, label9, label10, label11;
	private XdevGridLayout gridLayout;
	private PopupDateField popupDateField, popupDateField2;
	private XdevComboBox<CustomComponent> comboBox, comboBox2, comboBox4;
	private AbsoluteLayout absLayoutGPLX, absLayoutKiemDinh, absLayoutDangKy, absLayoutPhuongTien, absoluteLayout3;
	// </generated-code>
}
