package com.etc.bca_moto.ui;

import java.util.List;

import com.etc.bca_moto.dal.QdCuongCheKhauTruTienTuTk07DAO;
import com.etc.bca_moto.entities.QdCuongCheKhauTruTienTuTk07;
import com.vaadin.server.Resource;
import com.vaadin.ui.UI;
import com.xdev.reports.ExportType;
import com.xdev.reports.Report;
import com.xdev.ui.XdevBrowserFrame;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevView;

public class OutPut07PreView extends XdevView {

	/**
	 * 
	 */
	public OutPut07PreView() {
		super();
		this.initUI();
		final Object attribute = UI.getCurrent().getSession().getAttribute("OutPut07PreView");
		final String soQd = attribute.toString();
		final Report report = Report.New();
	
		final QdCuongCheKhauTruTienTuTk07DAO dao = new QdCuongCheKhauTruTienTuTk07DAO();
		final List<QdCuongCheKhauTruTienTuTk07> single_rec = dao.GetQdById(Long.parseLong(soQd));
         final String reportSrc = "WebContent/WEB-INF/resources/QD07.jrxml";
//		final String noiDungVPHC = single_rec.get(0).getCanCuBienBan();
//		final int lengthNdvp = noiDungVPHC.length();
//		if (lengthNdvp< 500)
//		{
//			reportSrc ="WebContent/WEB-INF/resources/QDTGGTTV18_A4.jrxml";
//		}
//		else if (lengthNdvp< 650)
//		{
//			reportSrc = ("WebContent/WEB-INF/resources/QDTGGTTV18_A4.jrxml");
//		}
//		else if (lengthNdvp < 800)
//		{
//			reportSrc = ("WebContent/WEB-INF/resources/QDTGGTTV18_A4.jrxml");
//		}
//		else if (lengthNdvp< 950)
//		{
//			reportSrc = ("WebContent/WEB-INF/resources/QDTGGTTV18_A4.jrxml");
//		} else {
//			reportSrc = ("WebContent/WEB-INF/resources/QDTGGTTV18_A4.jrxml");
//		}
		report.jrxml(reportSrc);
		report.dataSource(single_rec);
		final Resource resource = report.exportToResource(ExportType.PDF);
		this.browserFrame.setSource(resource);
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.browserFrame = new XdevBrowserFrame();
	
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(1);
		this.browserFrame.setSizeFull();
		this.gridLayout.addComponent(this.browserFrame, 0, 0);
		this.gridLayout.setColumnExpandRatio(0, 50.0F);
		this.gridLayout.setRowExpandRatio(0, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevBrowserFrame browserFrame;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
