
package com.etc.bca_moto.dal;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.ParameterExpression;
import javax.persistence.criteria.Root;

import com.etc.bca_moto.entities.QdXpvphc01;
import com.etc.bca_moto.entities.QdXpvphc01_;
import com.xdev.dal.JPADAO;

/**
 * Home object for domain model class QdXpvphc01.
 * 
 * @see QdXpvphc01
 */
public class QdXpvphc01DAO extends JPADAO<QdXpvphc01, Long> {
	public QdXpvphc01DAO() {
		super(QdXpvphc01.class);
	}

	/**
	 * @queryMethod Do not edit, method is generated by editor!
	 */
	public List<QdXpvphc01> findBySoQd(final String soQd) {
		final EntityManager entityManager = em();
	
		final CriteriaBuilder criteriaBuilder = entityManager.getCriteriaBuilder();
	
		final ParameterExpression<String> soQdParameter = criteriaBuilder.parameter(String.class, "soQd");
	
		final CriteriaQuery<QdXpvphc01> criteriaQuery = criteriaBuilder.createQuery(QdXpvphc01.class);
	
		final Root<QdXpvphc01> root = criteriaQuery.from(QdXpvphc01.class);
	
		criteriaQuery.where(criteriaBuilder.equal(root.get(QdXpvphc01_.soQuyetDinh), soQdParameter));
	
		final TypedQuery<QdXpvphc01> query = entityManager.createQuery(criteriaQuery);
		query.setParameter(soQdParameter, soQd);
		return query.getResultList();
	}
}